version: '3'
name: docker-development-setup
services:
  devcontainer:
    container_name: devcontainer
    build:
      context: devcontainer/
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available/php:/etc/nginx/sites-enabled/php
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./websites/:/var/www/
      - ./devcontainer/supervisord.conf:/etc/supervisor/supervisord.conf:ro
    command:
      - /usr/local/bin/supervisord

  mysql:
    container_name: mysql
    image: mysql:8.0.32-debian
    volumes:
      - mysql-data:/var/lib/mysq/
    environment:
      MYSQL_ROOT_PASSWORD: admin

volumes:
  mysql-data:
    name: mysql-data
